name: Push

# Evenement declancheur
on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      # Actions qui permet de récupérer le code associé à la branche de l'évènement
      - name: Checkout
        uses: actions/checkout@v7
        run: echo "Récupération du code"

      # Actions qui permet de configurer l'environnement de l'action
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0

      # Actions qui permet de mettre en cache les dépendances de l'application
      - name: Mise en cache
        uses: actions/cache@v5
        with:
         path: ~/.npm
         key: npm-${{ hashFiles('package-lock.json') }}

      # Actions qui permet de lancer les tests de l'application
      - name: Lancer les tests
        run: npm test
        env: 
          NODE_ENV: test

      # Actions qui permet d'afficher le status de l'action
      - if: always()
        run: echo "Status ${{ job.status }}"
          

      
